Add swap file creation support

diff --git a/fedberry-config b/fedberry-config
--- a/fedberry-config
+++ b/fedberry-config
@@ -18,9 +18,11 @@ BUG_REPORTS="https://github.com/fedberry/fedberry-config"
 
 ### Environment variables
 BOOT_DIR=/boot
+ETC_DIR=/etc
 CFG_TXT=$BOOT_DIR/config.txt
 CMD_TXT=$BOOT_DIR/cmdline.txt
 DTO_DIR=$BOOT_DIR/overlays
+FSTAB=$ETC_DIR/fstab
 
 
 ### Misc standard messages
@@ -539,6 +541,58 @@ pi_camera()
 }
 
 
+swap_add()
+{
+    #we need an argument
+    if [[ "$1" == "" ]]; then
+        echo "Missing argument"
+        return 0
+    fi
+        
+    #check for existing swap file
+    CHECK_SWAP=$(swapon --show --noheadings)
+    if [ "$CHECK_SWAP" != "" ]; then
+        msg_box "Existing swap file/partition found, can not proceed."
+        return 0
+    fi
+    
+    #check for sufficient disk space (swap + min 1GB extra?)
+    ROOTFS_INFO=( $(df |grep " /$") )
+    ROOTFS_FREE=$(echo ${ROOTFS_INFO[3]})
+    SWAP_REQ=$(($1 * 1024))
+    REQ_FREE=$(($SWAP_REQ + 1048576))
+    
+    if [ $ROOTFS_FREE -lt $REQ_FREE ]; then
+        msg_box "Insufficient free space on rootfs."
+        return 0
+    fi
+    
+    #create swap file & format it.
+    SWAP_MSG="Creating $1MB swap file, please wait..."
+    
+    if [ $NO_DIALOG -eq 1 ]; then
+        msg_box "$SWAP_MSG"
+        pv -p --size "$1"M /dev/zero | dd of=/swapfile bs=1k count="$1"k status=noxfer
+        mkswap /swapfile
+    else
+        (pv -n --size "$1"M /dev/zero | dd of=/swapfile bs=1k count="$1"k status=noxfer && mkswap /swapfile) 2>&1 | whiptail --gauge "$SWAP_MSG" 10 70 0
+    fi
+    
+    #could we use fallocate here as its much faster? or will we end up with a sparse file?
+    #Note: Btrfs does not support swap files and fallocate may cause problems with F2FS or XFS
+    #fallocate -l '$1'M /swapfile
+    
+    #world readable swap files are a huge local vulnerability
+    chmod 600 /swapfile
+    
+    #activate it
+    swapon /swapfile
+    
+    #enable it at boot
+    echo "/swapfile swap swap defaults 0 0" >>$FSTAB
+}
+
+
 rootfs_ask()
 {
     yes_no "Expand Root Filesystem" "Do you want to grow your root filesystem?\n\nWARNING: Before continuing, please save any work as the system will automatically reboot after re-partitioning"
@@ -607,6 +661,32 @@ rootfs_grow()
         # Don't want it running every boot as its job is already done.
         systemctl disable rootfs-grow.service
     fi
+}
+
+
+menu_swap()
+{
+    while true; do
+        SEL=$(whiptail --menu "Choose the swap file size" \
+        --backtitle "$NAME - $VERSION" \
+        --title "Swap File Selection Menu" $DLG_H $DLG_W $DLG_MH \
+        --ok-button Select \
+        "1. 256 MB " "Create and enable a 256MB swap file" \
+        "2. 512 MB " "Create and enable a 512MB swap file" \
+        "3. 1024 MB  " "Create and enable a 1024MB (1GB) swap file" \
+        3>&1 1>&2 2>&3)
+        RET=$?
+        if [ $RET == 1 ]; then
+            break
+        elif [ $RET == 0 ]; then
+            case "$SEL" in
+                1.*) swap_add 256; break ;;
+                2.*) swap_add 512; break ;;
+                3.*) swap_add 1024;break ;;
+                *) msg_box "Error: unrecognized option" ;;
+            esac || msg_box "There was an error running option $SEL"
+        fi
+    done
 }
 
 
@@ -718,7 +798,8 @@ menu_main()
         "2. DT Paramters  " "Enable or disable Device Tree (DT) parameters" \
         "3. Hardware Support  " "Enable or disable hardware support / drivers" \
         "4. Expand Root FS  " "Expand (grow) root filesystem on SD card" \
-        "5. About $NAME  " "Information about this configuration tool" \
+        "5. Add Swap File  " "Add and enable a swap file" \
+        "6. About $NAME  " "Information about this configuration tool" \
         3>&1 1>&2 2>&3)
         RET=$?
         if [ $RET == 1 ]; then
@@ -729,7 +810,8 @@ menu_main()
                 2.*) menu_params ;;                
                 3.*) menu_drivers ;;
                 4.*) rootfs_ask ;;
-                5.*) about ;;
+                5.*) menu_swap ;;
+                6.*) about ;;
                 *) msg_box "Error: unrecognized option" ;;
             esac || msg_box "There was an error running option $SEL"
         else
@@ -846,6 +928,9 @@ case $1 in
     "--rootfs-grow")
         NO_DIALOG=1
         rootfs_grow ;;
+    "--add-swap")
+        NO_DIALOG=1
+        swap_add $2;;
     "--version")
         echo "$NAME - Version: $VERSION" ;;
     "")
